### ISSUE TITLE
In search page, inside the quick view, the addtocart button is not working. 

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Karan-Patel-Retail---Internal--May-4-#10]
**Actual result:** 
In search page, inside the quick view, the addtocart button is not working. 
![image](https://user-images.githubusercontent.com/102131636/165895899-ee7bfade-b403-4b05-b7d2-d2320b4cd9f1.png)

**Expected result:** 
The addtocart butto have to be working.

**Comment by ui-rishavkumar** [comment]
@sudhanshu0603 add to cart button is working properly on those product who are not sold out

**Comment by sudhanshu0603** [comment]
ok ,resolved
