### ISSUE TITLE
The the quantity box inside the quick view in search page, the designing of input field is not equal.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Karan-Patel-Retail---Internal--May-4-#11]
**Actual result:** 
The the quantity box inside the quick view in search page, the designing of input field is not equal.
When we are clicking on the input field of the quantity then the quantity is increasing.
The video issue: https://www.awesomescreenshot.com/video/8659552?key=b8f9cb439d35a115bb975abd679e383b
![image](https://user-images.githubusercontent.com/102131636/165896396-95b04293-4059-4674-8851-00e6ed5fc756.png)

**Expected result:** 
The quantity input field have to be working properly on clicking, the quantity is increasing on clicking it should not work like this.

**Comment by ui-rishavkumar** [comment]
@sudhanshu0603 from my end design was done

**Comment by sudhanshu0603** [comment]
ok resolved
