### ISSUE TITLE
RESET password without filling the email when we hover over the submit button then the disabled symbol have to come.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Karan-Patel-Retail---Internal--May-4-#14]
**Actual result:** 
1: The disabled symbol is not coming without filling the email when we are hovering over the submit button.
2: We will send a email to reset the password text is starting from the left side.
![image](https://user-images.githubusercontent.com/102131636/165900881-34ac3422-2c78-461d-8e48-f9f6f3aa0036.png)

**Expected result:** 
RESET password without filling the email when we hover over the submit button then the disabled symbol have to come.
2: We will send a email to reset the password text is starting from the left side, it can be aligned in the middle it will be much better.

**Comment by ui-rishavkumar** [comment]
@sudhanshu0603  now text will be center

**Comment by sudhanshu0603** [comment]
ok ,resolved
