### ISSUE TITLE
In account page after successfull login, when we click on the edit and many input fields are empty and when we are clicking on the update address then form is submitting.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Karan-Patel-Retail---Internal--May-4-#16]
**Actual result:** 
In account page after successfull login, when we click on the edit and many input fields are empty and when we are clicking on the update address then form is submitting.
no validation are added.
![image](https://user-images.githubusercontent.com/102131636/165902038-6d64b55e-3b83-4f55-9ab1-d2cf35e62f61.png)

**Expected result:** 
Validation have to be used for the address page.
form should not submit without filling the form.

**Comment by devSuneel** [comment]
I validate only needed fields like
first name
last name
mobile no
email

**Comment by sudhanshu0603** [comment]
please login then click on the view address then in this page the validation are not added. @devSuneel

**Comment by sudhanshu0603** [comment]
ok, resolved

**Comment by devSuneel** [comment]
@sudhanshu0603 no need to make it more complex we normally do validation for the first name, last name and mobile number must be number, it should be user friendly

**Comment by sudhanshu0603** [comment]
ok fine as discussed.
