### ISSUE TITLE
When we are clicking on this banner then it is opening the about us page.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Karan-Patel-Retail---Internal--May-4-#20]
**Actual result:** 
When we are clicking on this banner then it is opening the about us page.
![image](https://user-images.githubusercontent.com/102131636/165906492-be615f2b-3804-4303-a22b-afbb660e5985.png)
![image](https://user-images.githubusercontent.com/102131636/165906532-f24b0384-2ab7-4798-b132-b188984da823.png)

**Expected result:** 
When we clicking on the banner then it should open the page related to it.

**Comment by devSuneel** [comment]
It is linked to the right page

**Comment by sudhanshu0603** [comment]
need to be discussed

**Comment by sudhanshu0603** [comment]
ok resolved
