### ISSUE TITLE
In collection page, some of the collection images are not added.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Karan-Patel-Retail---Internal--May-4-#21]
**The url:** 
https://greatbuysales.myshopify.com/collections/

**Actual result:** 
In collection page, some of the collection images are not added.
![image](https://user-images.githubusercontent.com/102131636/165907483-23a6e6ec-a525-438e-9f10-1b0870f470b9.png)

**Expected result:** 
The collection images have to be added.

**Comment by devSuneel** [comment]
product is not available in the 
collection

**Comment by sudhanshu0603** [comment]
needs to be discussed.

**Comment by sudhanshu0603** [comment]
ok resolved
