### ISSUE TITLE
In cart page, the checkout and clear cart button have to be of different color it will be much better.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Karan-Patel-Retail---Internal--May-4-#27]
**Actual result:** 
In cart page, the checkout and clear cart button have to be of different color it will be much better.
![image](https://user-images.githubusercontent.com/102131636/165913958-9dd70f22-f74d-4eba-8265-fe3b5a781991.png)

**Expected result:** 
The color of the button for clear cart and check out have to be differnt i will be much better.

**Comment by ui-rishavkumar** [comment]
@sudhanshu0603 sir as we can follow a same pattern in whole site for button thats why we use here same background pattern for button

**Comment by sudhanshu0603** [comment]
ok ,
