### ISSUE TITLE
The social media links are missing in the footer section .

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Karan-Patel-Retail---Internal--May-4-#31]
**Actual result:** 
The social media links are missing in the footer section .
**Expected result:** 
The social media links can be added in the footer

**Comment by devSuneel** [comment]
link is not provided by the client

**Comment by sudhanshu0603** [comment]
ok ,in its wholesale  store we have the link,  this we will discuss. what we will do .

**Comment by Shweta-PC** [comment]
@sudhanshu0603  Page is under constrution dur to which he doesn't have pages for now. we will be sharing the video with client so that he can add them on later basis

**Comment by sudhanshu0603** [comment]
as discuseed client end
