### ISSUE TITLE
The currency converter, language converter and chatbot can be added in the store.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Karan-Patel-Retail---Internal--May-4-#32]
**Actual result:** 
The currency converter, language converter and chatbot can be added in the store.
**Expected result:** 
Mentioned app can be added in the store.

**Comment by sudhanshu0603** [comment]
not added @devSuneel 
![image](https://user-images.githubusercontent.com/102131636/166097214-252b3e7d-3f27-4345-a0b2-bd83d649c5a3.png)

**Comment by devSuneel** [comment]
@sudhanshu0603 currency converter and language converter already added in store but sometimes it does not appear in the preview when site will live then it will appear automatically

**Comment by sudhanshu0603** [comment]
will check on live.
