### ISSUE TITLE
The unwanted review can be removed from the product page.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Karan-Patel-Retail---Internal--May-4-#34]
The url: https://greatbuysales.myshopify.com/products/test-product
**Actual result:** 
The unwanted review can be removed from the product page.
![image](https://user-images.githubusercontent.com/102131636/165922350-15a740c0-2ca5-4469-8cf8-452c594b18fc.png)

**Expected result:**
The review can be removed which were of no use.

**Comment by devSuneel** [comment]
resolved

**Comment by sudhanshu0603** [comment]
ok ,resolved
