### ISSUE TITLE
For the collection page , left side blank box should not be visible .

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Karan-Patel-Retail---Internal--May-4-#35]
**actual result:** 
For the collection page , left side blank box should not be visible .
![image](https://user-images.githubusercontent.com/102131636/165923092-3e1bd663-56d6-40bf-a726-c79612a57b9a.png)

**Expected result:** 
The blank box should not coming when there is no product in the collection.

**Comment by devSuneel** [comment]
https://7ubd1rr4dzcka05h-63646400733.shopifypreview.com
resolved

**Comment by sudhanshu0603** [comment]
ok, resolved
