### ISSUE TITLE
When we hover over the home and kitchen then the image is missing. 

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Karan-Patel-Retail---Internal--May-4-#36]
**Actual result:** 
When we hover over the home and kitchen then the image is missing. 
![image](https://user-images.githubusercontent.com/102131636/165923786-82158f5c-62ec-40c2-bbb5-2e38b51fed88.png)

**Expected result:** 
All the images have to be added .

**Comment by devSuneel** [comment]
collection does not have any product

**Comment by sudhanshu0603** [comment]
need discusion.

**Comment by Shweta-PC** [comment]
@sudhanshu0603  THis is not an error . Once client will add products the image will reflect . currently the stock is empty and client needs time to upload same.

**Comment by sudhanshu0603** [comment]
ok ,resolved
