### ISSUE TITLE
In home page, the collection images are added but when we click on the shop now button then it is opening the different page.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Karan-Patel-Retail---Internal--May-4-#37]
**Actual result:** 
In home page, the collection images are added but when we click on the shop now button then it is opening the different page.

**The video issue :** 
https://www.awesomescreenshot.com/video/8662809?key=719bedf346de1ffe59a48ee4332f8713
![image](https://user-images.githubusercontent.com/102131636/165924938-dc2f42ec-87dd-4071-82db-db954c4090ae.png)

**Expected result:** 
When we are clicking on the some of the shop now button then it is opening the different collection page.

**Comment by devSuneel** [comment]
resolved

**Comment by sudhanshu0603** [comment]
ok ,resolved
