### ISSUE TITLE
In product, the button of wishlist text is coming in 2 line if it can be aligned in single line then it will be much better.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Karan-Patel-Retail---Internal--May-4-#46]
**Actual result:** 
The wishlist button text is coming in 2 lines.
![image](https://user-images.githubusercontent.com/102131636/165946372-259c4b87-8ce2-434b-9e5e-017c9ede30c6.png)

Expected result: 
In product, the button of wishlist text is coming in 2 line if it can be aligned in single line then it will be much better.

**Comment by devSuneel** [comment]
it depends on the screen and the text is automatically adjusted according to a screen that's why coming in the second line

**Comment by sudhanshu0603** [comment]
ok ,resolved
