### ISSUE TITLE
The 2nd collection is not working on clicking.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Karan-Patel-Retail---Internal--May-4-#47]
**Steps:**
1: Click on the hambergur > accessories >guids & guards.
2: Click on the hambergur> accessories?>Enhancement tools , then the page will not load in mobile view.
**Actual result:** 
2nd time when we use the hambergur option then the page is not loading.
**The video issue:** 
https://www.awesomescreenshot.com/video/8665725?key=a538e97d6de58ba8f4207765e8063c68
![image](https://user-images.githubusercontent.com/102131636/165948138-c36ecdde-9963-4c5b-b62c-5b69754f39f4.png)

**Expected result:** 
The collection inside the hambergur, when we click on the option then the all the collection pages have to be load.

**Comment by devSuneel** [comment]
resolved

**Comment by sudhanshu0603** [comment]
ok, resolved
