### ISSUE TITLE
In search page when we click on the wishlist icon inside the quick view then the modal of wishlist is opening behind the quick view modal.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Karan-Patel-Retail---Internal--May-4-#5]
**Actual result:**
In search page when we click on the wishlist icon inside the quick view then the modal of wishlist is opening behind the quick view modal.
![image](https://user-images.githubusercontent.com/102131636/165893644-4f2144a8-7b52-49a1-bdf4-91154197decb.png)

**Expected result:** 
The 2 modals are added quick view and wishlist it needs to be verified the opening of modals.

**Comment by devSuneel** [comment]
no need to add wishlist in Quickview so I removed wishlist from Quickview page

**Comment by sudhanshu0603** [comment]
ok, resolved
