### ISSUE TITLE
In mobile view, the when we are searching the random name then the filters are visible on the search page, it can be disabled when there is no product.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Karan-Patel-Retail---Internal--May-4-#51]
**Actual result:**
In mobile view, the when we are searching the random name then the filters are visible on the search page, it can be disabled when there is no product.
![image](https://user-images.githubusercontent.com/102131636/166093570-d8dacc11-562d-463b-b555-3d66762adc3b.png)

**Expected result:**
There is no need of the filters in sortby if there is not product in the search page, we can remove it .

**Comment by devSuneel** [comment]
https://nzn6othvwhxy6pqr-63646400733.shopifypreview.com

**Comment by sudhanshu0603** [comment]
ok, resolved
