### ISSUE TITLE
When we type the tr in the search page then the privacy policy page are coming.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Karan-Patel-Retail---Internal--May-4-#7]
**Actual result:** 
When we type the tr in the search page then the privacy policy page are coming.
![image](https://user-images.githubusercontent.com/102131636/165894137-799c6f5f-a4d3-40f7-9040-a999ed70d0bf.png)

**Expected result:** 
The policy pages should not be added in the search page.

**Comment by devSuneel** [comment]
it is used for searching so 
it will search everything like
product
pages
article

**Comment by sudhanshu0603** [comment]
need to be discussed

**Comment by sudhanshu0603** [comment]
ok,  as discussed with the @devSuneel
