### ISSUE TITLE
In search page, in quick view page, when we hover over the  + and - of quantity then the hand cursor is not coming.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Karan-Patel-Retail---Internal--May-4-#9]
**Actual result:** 
In search page, in quick view page, when we hover over the  + and - of quantity then the hand cursor is not coming.
The empty quantity field is coming.
![image](https://user-images.githubusercontent.com/102131636/165895368-e8a47be9-e623-455b-b398-f0d8f4ceca0b.png)
![image](https://user-images.githubusercontent.com/102131636/165895734-047bc730-02a0-4bcd-8502-6d4311aa8467.png)

**Expected result:** 
In search page, in quick view page, when we hover over the  + and - of quantity then the hand cursor have to coming.

**Comment by ui-rishavkumar** [comment]
@sudhanshu0603  hand cursor issue was done

**Comment by sudhanshu0603** [comment]
ok, resolved
